[package]
name = "send-it"
version = "0.1.0"
edition = "2021"
authors = ["Eric <skepz.dev@gmail.com>"]
description = "A tool for sending large amounts of data over a network."
license = "MIT"
repository = ""

[dependencies]
